### PR TITLE
Publish only ZIP artifacts since the plugin has no xxx-client counterpart

### PR DESCRIPTION
**Pull request by reta**
### Description
Publish only ZIP artifacts since the plugin has no xxx-client counterpart

```
$ ./scripts/build.sh -s true -v 3.0.0
```

```
$ tree build/local-staging-repo/org/opensearch/
build/local-staging-repo/org/opensearch/
└── plugin
    └── opensearch-custom-codecs
        ├── 3.0.0.0-SNAPSHOT
        │   ├── maven-metadata.xml
        │   ├── maven-metadata.xml.md5
        │   ├── maven-metadata.xml.sha1
        │   ├── maven-metadata.xml.sha256
        │   ├── maven-metadata.xml.sha512
        │   ├── opensearch-custom-codecs-3.0.0.0-20231004.151629-1.pom
        │   ├── opensearch-custom-codecs-3.0.0.0-20231004.151629-1.pom.md5
        │   ├── opensearch-custom-codecs-3.0.0.0-20231004.151629-1.pom.sha1
        │   ├── opensearch-custom-codecs-3.0.0.0-20231004.151629-1.pom.sha256
        │   ├── opensearch-custom-codecs-3.0.0.0-20231004.151629-1.pom.sha512
        │   ├── opensearch-custom-codecs-3.0.0.0-20231004.151629-1.zip
        │   ├── opensearch-custom-codecs-3.0.0.0-20231004.151629-1.zip.md5
        │   ├── opensearch-custom-codecs-3.0.0.0-20231004.151629-1.zip.sha1
        │   ├── opensearch-custom-codecs-3.0.0.0-20231004.151629-1.zip.sha256
        │   └── opensearch-custom-codecs-3.0.0.0-20231004.151629-1.zip.sha512
        ├── maven-metadata.xml
        ├── maven-metadata.xml.md5
        ├── maven-metadata.xml.sha1
        ├── maven-metadata.xml.sha256
        └── maven-metadata.xml.sha512
```

### Issues Resolved
Closes https://github.com/opensearch-project/custom-codecs/issues/68

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by reta** [comment]
@gaiksaya fyi

**Comment by reta** [comment]
> The problematic pom was /org/opensearch/opensearch-custom-codecs/2.10.0.0/opensearch-custom-codecs-2.10.0.0.pom

Correct @gaiksaya , it is gone now, we don't need to publish this JAR

**Comment by prudhvigodithi** [comment]
Hey @reta apart from what @gaiksaya  said, lets not remove the jar publish as some users might directly use the Jar (import) and move forward with the development or use the jar to address dependencies. Example I can directly use the https://aws.oss.sonatype.org/content/repositories/releases/org/opensearch/opensearch-custom-codecs/2.10.0.0/

```
mvn org.apache.maven.plugins:maven-dependency-plugin:2.1:get -DrepoUrl=https://aws.oss.sonatype.org/content/repositories/releases/ -Dartifact=org.opensearch:opensearch-custom-codecs:2.10.0.0
Picked up JAVA_TOOL_OPTIONS: -Dlog4j2.formatMsgNoLookups=true
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------< org.apache.maven:standalone-pom >-------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.1:get (default-cli) @ standalone-pom ---
Downloading from central: https://repo.maven.apache.org/maven2/org/opensearch/opensearch-custom-codecs/2.10.0.0/opensearch-custom-codecs-2.10.0.0.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/opensearch/opensearch-custom-codecs/2.10.0.0/opensearch-custom-codecs-2.10.0.0.jar (27 kB at 72 kB/s)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.800 s
[INFO] Finished at: 2023-10-04T10:15:10-07:00
[INFO] ------------------------------------------------------------------------
```

WDYT?
@bbarani @peterzhuamazon

**Comment by reta** [comment]
> Hey @reta apart from what @gaiksaya said, lets not remove the jar publish as some users might directly use the Jar (import) and move forward with the development or use the jar to address dependencies.

There is absolutely no need to use JAR, some plugins do have xxx-client artifacts, this plugin has not, we should not publish just JAR for no reason.

**Comment by prudhvigodithi** [comment]
> Hey @prudhvigodithi , there is absolutely no need to use this JAR, some plugins do have xxx-client artifacts, this plugin has not, we should not publish just JAR for no reason.

Sure @reta just bought it up to ensure we dont impact users who use jars.

**Comment by reta** [comment]
> Sure @reta just bought it up to ensure we dont impact users who use jars.

Thanks @prudhvigodithi , I see no circumstances under which the JAR could be useful as it is now.

**Comment by reta** [comment]
@andrross need your signoff please

**Review by andrross — APPROVED** [review]

**Pull request merged**
