### PR TITLE
Add workflow to publish snapshots to maven

### PR DESCRIPTION
**Pull request by gaiksaya**
### Description
Adds workflow to publish snapshots to maven. Tested locally:

```
[root@dcda507af0e2 snapshots]# tree org
org
`-- opensearch
    `-- plugin
        `-- custom-codecs
            |-- 3.0.0.0-SNAPSHOT
            |   |-- custom-codecs-3.0.0.0-20230908.172334-1.pom
            |   |-- custom-codecs-3.0.0.0-20230908.172334-1.pom.md5
            |   |-- custom-codecs-3.0.0.0-20230908.172334-1.pom.sha1
            |   |-- custom-codecs-3.0.0.0-20230908.172334-1.pom.sha256
            |   |-- custom-codecs-3.0.0.0-20230908.172334-1.pom.sha512
            |   |-- custom-codecs-3.0.0.0-20230908.172334-1.zip
            |   |-- custom-codecs-3.0.0.0-20230908.172334-1.zip.md5
            |   |-- custom-codecs-3.0.0.0-20230908.172334-1.zip.sha1
            |   |-- custom-codecs-3.0.0.0-20230908.172334-1.zip.sha256
            |   |-- custom-codecs-3.0.0.0-20230908.172334-1.zip.sha512
            |   |-- maven-metadata.xml
            |   |-- maven-metadata.xml.md5
            |   |-- maven-metadata.xml.sha1
            |   |-- maven-metadata.xml.sha256
            |   `-- maven-metadata.xml.sha512
            |-- maven-metadata.xml
            |-- maven-metadata.xml.md5
            |-- maven-metadata.xml.sha1
            |-- maven-metadata.xml.sha256
            `-- maven-metadata.xml.sha512
```

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._ 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by reta — APPROVED** [review]

**Comment by reta** [comment]
@gaiksaya the workflow fails with:

```
Run aws-actions/configure-aws-credentials@v1
Error: Credentials could not be loaded, please check your action inputs: Could not load credentials from any providers

```

https://github.com/opensearch-project/custom-codecs/actions/runs/6124719396

**Comment by gaiksaya** [comment]
YEah just configured it. @reta why is the name of the artifact `custom-codecs` and not `opensearch-custom-codecs`

**Comment by reta** [comment]
> YEah just configured it. @reta why is the name of the artifact `custom-codecs` and not `opensearch-custom-codecs`

Let me fix that, one sec

**Comment by gaiksaya** [comment]
I removed the secret to avoid publishing at wrong co-ordinates. Let me know when its fixed. Will add back.
Thanks!

**Comment by gaiksaya** [comment]
Hi @reta @andrross 

The run was successful: https://github.com/opensearch-project/custom-codecs/actions/runs/6125315641
I believe custom -codecs is still being published from core repo https://github.com/opensearch-project/OpenSearch/tree/2.10/plugins/custom-codecs
so previous artifacts still exists and will keep overwriting. 
In terms of workflow and publishing via this repo we are good.

**Comment by reta** [comment]
I also checked that, looked good, thanks @gaiksaya !

**Pull request merged**
