### PR TITLE
Add release notes for 2.14

### PR DESCRIPTION
**Pull request by soosinha**
### Description
Add release notes for 2.14

### Issues Resolved
NA

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by sarthakaggarwal97** [comment]
Build is failing, have retried. Looks like the OpenSearch artifact is missing.

**Comment by reta** [comment]
> Thanks @soosinha for raising this. Build is failing, have retried. Looks like the OpenSearch artifact is missing.

No, it is GA MacOS agent change: the macos latest is now on arm64, I will submit a fix shorlty

**Comment by reta** [comment]
@soosinha could you rebase please? thank you

**Comment by soosinha** [comment]
@reta I have rebased but now bwc checks are failing.

**Comment by reta** [comment]
> @reta I have rebased but now bwc checks are failing.

Thank you @soosinha , seems to be caused by `HTTP/503`

**Comment by reta** [comment]
> Thank you @soosinha , seems to be caused by `HTTP/503`

Aha, some mixed cluster formation is failing ... Need to look into it ...

**Review by sarthakaggarwal97 — APPROVED** [review]
BWC tests were failing due to minimum wire compatibility.

**Pull request merged**
